### ISSUE TITLE
Determining if player or not

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#19]
So the player is an actual entity in the game. The Human class needs to know which human this is. Right now, if length of the people list is zero, it is assumed that the human being created is the player. This seems fragile to me and I would like to develop a safer system for referring to the player. 
Maybe store the player name and surname as a global variable and comparing it to the name of each person referenced.

**Comment by Talkyn** [comment]
Why does it need to know this?  I see you have it set up to create the player version only when the people list is empty, but why do it this way when we can specifically create a player instance and clean a logic chain out of the init method of human?  Refer to my other reply also, since it could very well be as simple as just instancing the player separately.  You can even leave all the player-specific stats in place by giving them default None values.  That way, only the player instance, which has these values assigned, is seen to have them.

I would actually propose solving this with inheritance.  Make the Human class have everything human, and create a Player(Human) class that adds the player functionality.

**Comment by dis446** [comment]
Thanks. I actually had the same idea and was working on it for the last hour or so. I just committed new sub-classes. One for the player and one for the NPC. It's still not working properly, but I think this is the solution.

**Comment by sgtlaggy** [comment]
The Player and NPC classes could both go in the Human module. Maybe even use inheritance?

**Comment by dis446** [comment]
They do use inheritance. But moving them into the Human.py file would be fine.

**Comment by dis446** [comment]
Just for note:
Use this to determine if an object is a player or not

if isinstance(human, Player):
