### ISSUE TITLE
Partition code more?

### ISSUE THREAD

**Issue by dis446** [dis446/Fallout-Shelter-Text-Based#28]
So since I've been receiving help from contributors, the source code has gotten more and more fragmented, into several separate source files that are imported by the main file. I am considering breaking it up even more. Currently, the functions in the main file are divided into logical units/systems. It's annoying to manually scroll through the code. 
If this were to be implemented, the source files would look something like this:

main.py
// All the classes(Human, item etc)
general_funcs.py // This already exists
human_management.py //Scavenging would probably be merged into this...
item_management.py
etc.

And only some of the current systems would remain. I see no reason to move the choice and trading systems, as they are both just one function.

So. Thoughts? My concern is that it will shatter the code into 10 fragments ( but it will be easier to navigate).

**Comment by sgtlaggy** [comment]
I like keeping module names short and descriptive whenever possible. Also having a capital first letter in the module names prevents most conflicts with official python and pypi packages.

**Comment by dis446** [comment]
Yeah fine, but do you think the systems should be separated into modules?

**Comment by sgtlaggy** [comment]
What do you mean by systems?

**Comment by dis446** [comment]
I grouped functions into what I call game 'systems'.
I.e. the human management system has the functions that deal with birth, death, get_person_index() 
while the inventory management system has count_item(x), add_to_inven(x) etc.

**Comment by sgtlaggy** [comment]
Yeah, that's the general idea, although if, say, get_person_index() was also referenced by room objects, it would have to go in general_funcs. This is because if you had separate item/room/human modules _just_ for their respective functions, they would eventually require importing each other and the interpreter doesn't like that, because of infinite import loops.

**Comment by dis446** [comment]
Yeah, we have to be careful of that. We can make sure functions such as get_person_index() is only called in the main game file. I think I will make a branch and partition the game there, to see how it works.

**Comment by sgtlaggy** [comment]
Please always make a new branch when making changes, then merge it into master once it's complete and working.

**Comment by dis446** [comment]
Sound advice actually.

**Comment by sgtlaggy** [comment]
For a small example, count_item will be going in Room.py (unless we decide other functions calling it should be in general_funcs) because it's only used there and in the main module.

**Comment by sgtlaggy** [comment]
Few questions on this:
- Should functions that don't belong in Human/Item/Room be moved into general_funcs or left in Fallout_Shelter?
- Should inventory functions go in Inventory or Item?

**Comment by kungtotte** [comment]
I think it would be better to rethink the overall design first (including deglobalization) and then move code into whatever modules make sense.

In general a more idiomatic way of doing it is to have the top level module call out to the other modules and sort of gather everything up, and to use short module names whenever possible.

For example:

``` python
import Humans
import Rooms

# creating people 
player = Humans.Human(player=True)
for _ in range(0,6):
    p = Humans.Human(Humans.random_name())
    people[str(p)] = p # store with name as key and the object as value 

# using rooms
for r in built_rooms:
    room.consume("watt", resources) # deduct watts from the resources object 
    resource, production = room.produce()
    resources[resource] += production 
    r.toggle_rushed()

if room_type not in built_rooms:
    r = Rooms.Room(room_type)
    built_rooms.append(r)
```

I posted an example in the deglobalization issue too.

Generally speaking methods and functions should have no side effects whenever possible. That is they take some input and return some output, and then the caller decides what to print (for example)

Use Python data structures instead of making our own, because then the language will work for us instead of against us.

I haven't had time to do it yet but I can sketch out a basic way of doing things. I might have some time tomorrow after work.

**Comment by mikevb1** [comment]
I'm putting together a big change right now. Inventory class extending list with current functions instead of having functions you pass inventories into. Also moving functions into appropriate modules, and simplifying lots of functions.

**Comment by dis446** [comment]
Fine. Let's hold of the code partitioning.
